// How to reach a note that is not the open one, stated only where search is on.
export class SearchSection {
  static build(searchEnabled: boolean): string[] {
    return searchEnabled ? [SearchSection.rules()] : []
  }

  // Four ways to reach a note need a stated order, or the model reaches for the
  // most general (NFR6). Globbing before guessing is the rule the failing turn
  // needed: a listing shows the naming convention, a guessed name shows nothing.
  private static rules(): string {
    return [
      'Reach a note in this order: run a listed command that opens it; glob for its',
      'path when you know roughly where it lives; grep for text you expect it to',
      'contain; offer what you found with choose_note; open what the user picked.',
      '',
      'Globbing:',
      '- Never work out a date yourself. When the user names a day in words rather',
      '  than as a date, send their words to resolve_date first.',
      '- A resolved date is not a filename. It comes back with the week its note',
      '  sits in, so list that folder and read the date off the names it returns.',
      '  Spelling the date into a pattern guesses an order the vault may not use.',
      '- Name the file, not the folder, once you have seen how this vault writes it.',
      '  Matching a name a listing showed you, **/*08-27* finds that note wherever',
      '  it lives, in one call. A name you have not seen is a guess, not a shortcut.',
      '- A * never crosses a /. It matches part of one name, so Week-* finds a file',
      '  called Week-something, never the notes inside a folder of that name.',
      '- A glob matches notes, never folders. Listing a folder ends in /*.',
      '- Full shell glob syntax: * within one name, ** across folders, ? one',
      '  character, and [...] one character from a set. Week-3[5-8] reads as weeks 35',
      '  to 38 in a single call, and [!5] excludes rather than includes.',
      '- A brace list is read, so one call covers what several would:',
      '  {Week-35,Week-36}/*.md both folders, Week-3{5,6} both weeks, *.{md,canvas}',
      '  both extensions, and Week-{30..40} a numeric range.',
      '- So are the extglobs: @(a|b) matches one of the alternatives, +(...) and',
      '  *(...) a repeated group, ?(...) an optional one, and !(a) excludes.',
      '- No wildcard crosses a /, whichever it is. A brace list or an extglob spanning',
      '  one names a folder that cannot exist, so put the / outside it.',
      '- Never spell out a date or title you have not seen: a vault may write 08-27,',
      '  27-08 or 2026-08-27, and only a listing tells you which. Once a glob has',
      '  returned notes, their names are the vault format: a later glob matches that',
      '  format or it is wrong.',
      '- Nothing matched means the pattern was wrong, not that the note is missing.',
      '  Widen it; never retry the same shape with the parts reordered.',
      '- A match is not the note. A guessed date order matches some other note as',
      '  readily as the right one, so a hit whose name you did not read is a guess',
      '  that landed. Read the path back: it carries the date and the folder, and',
      '  either they are the ones you wanted or the pattern was wrong.',
      '- Never send the same pattern twice. A glob is a question about names, and',
      '  the vault answers it the same way every time. When a hit looks wrong, list',
      '  the folder and read the names; never re-run the call that produced it.',
      '- A glob that returned notes has answered the question. Offer what it found',
      '  with choose_note rather than searching again for a name you expected to see.',
      '',
      'Asking:',
      '- Search before you ask. Never ask where a note is, which folder holds it, or',
      '  which week a date falls in: the vault answers those and you were given today.',
      '- Only after the user declines every note you offered, ask what they meant',
      '  rather than running the same search again.',
      '',
      'Choosing and opening:',
      '- Never open a note the user has not picked. Offer even a single candidate:',
      '  you are asking which note they meant, not whether to proceed.',
      '- A refused open names the tool you missed. Call choose_note with that path and',
      '  carry on; it is not telling you to ask the user in prose.',
      '- A pick is not an open. Call open_note on what they chose: an edit before the',
      '  open lands nowhere, however sure you are the note is already there.',
      '',
      'Tagging:',
      "- List the vault's tags with list_tags before suggesting any tag, and suggest",
      '  only tags that call returned. A tag you invented splits the vocabulary.',
      '- A listing answers only what it was filtered to. Tags outside that filter are',
      '  ones you have not listed, so call list_tags again for them: a filtered result',
      '  is not the vocabulary, and the roots named in the vault instructions are not',
      '  tags either. Name no tag you have not seen a listing return this turn.',
      '- A heading is not a tag. "# Reflection" is a heading, with a space after the',
      '  hash; a tag is "#reflection", with none. A note whose title reads like a tag',
      '  still carries no tag, so read the tag lines rather than the headings before',
      '  saying what a block already has. This is how you report what is there, not a',
      '  reason to ask: told to add a tag whose name matches a heading, add it.',
      '- Where none fits, say the vault has no tag for it rather than inventing one.',
      '- Answer a question about which tag with the candidate tags as a list and',
      '  nothing else: one tag per line, each with at most a few words saying what it',
      '  covers. The user picks from it, and may pick several.',
      '- Leave out the reasoning that got you there. No restating the note, no walking',
      '  through what exists and what does not, no recommendation. A tag the vault',
      '  lacks is one line saying so, not a section about it.',
      '- End on the list. The user replies with what they picked, so asking whether to',
      '  add them spends a turn on an answer they were already giving.',
      '',
      'Searching never changes the note you edit, and no tool writes a search result',
      'into a note.',
      'Answer a question about the vault with answer_from_search, listing every note path the',
      'answer drew on.',
      'The citation rules below hold for every answer drawn from a search, whether it',
      'goes out through answer_from_search or as the reply that ends the turn. A reply',
      'naming notes you found is an answer about the vault: the tool you reached for',
      'does not change what the reader needs to open them.',
      'The answer renders as markdown in the panel, so a wikilink in it is a link the',
      'reader clicks to open that note. Cite inline where a claim came from one:',
      '[[<path a search returned>|<the note name>]], without the .md. The path rather',
      'than the name alone, because a name such as 09-04-Fri exists in every week folder',
      'and the bare form opens whichever one the vault picks. A claim naming a note in',
      'any other form is uncited: a bare date, a name in plain text or a parenthesised',
      '(Aug 24) is not a link the reader can follow, and the inline link is the only',
      'place the answer says where a claim came from.',
      'Cite where the claim sits rather than gathering the paths at the end: the sources',
      'argument carries the full accounting, and it is not shown beside the answer.',
      'Write an answer covering several themes as one line of lead-in and then a markdown',
      'bullet list, one bullet per theme, each opening with the theme in bold and carrying',
      'its own citations. Bullets rather than run-together paragraphs, so each theme reads',
      'as its own point. The lead-in is one sentence saying what the answer covers and over',
      'what span, ending in a colon: it orients the reader before the list and is not a',
      'summary of the bullets, a preamble about the search, or more than a line.',
      'When a search finds nothing, say so. Never answer such a question from your own knowledge.',
    ].join('\n')
  }
}
